"""removed role

Revision ID: a5097e5577b0
Revises: 27ead30731c9
Create Date: 2021-07-31 00:37:17.315497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5097e5577b0'
down_revision = '27ead30731c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_role', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
